# Auto-detect screen resolution
monitor=,preferred,auto,1

# Auto-start our multiplayer daemon!
exec-once = python /opt/mmos/overlay.py

# Set a custom background color (Dark grey so we can see the red squares)
exec-once = hyprctl setcursor left_ptr 24

# Basic Keybinds so you can actually use the OS
bind = SUPER, Q, exec, kitty
bind = SUPER, M, exit,
