# Auto-detect screen resolution
monitor=,preferred,auto,1

# Auto-start our launcher script!
exec-once = bash /opt/mmos/start_mmos.sh

# Set a custom background color (Dark grey so we can see the red squares)
exec-once = hyprctl setcursor left_ptr 24

# Basic Keybinds so you can actually use the OS
bind = SUPER, Q, exec, kitty
bind = SUPER, M, exit,
ecosystem {
    no_warnings = true
    no_update_news = true
}
